controller_manager:
  ros__parameters:
    update_rate: 50
    robot_description: /robot_description
    controllers:
      - name: diff_drive_controller
        type: "diff_drive_controller/DiffDriveController"
        publish_rate: 50
        wheel_separation: 0.34
        wheel_radius: 0.1
        left_wheel: 'left_wheel_joint'
        right_wheel: 'right_wheel_joint'
        cmd_vel_timeout: 0.25
        publish_tf: true
        velocity_rolling_window_size: 2
        enable_odom_tf: true
        linear:
          x:
            has_velocity_limits    : true
            max_velocity           : 2.0
            min_velocity           : -2.0
            has_acceleration_limits: true
            max_acceleration       : 3.0
            min_acceleration       : -3.0
            has_jerk_limits        : true
            max_jerk               : 5.0
            min_jerk               : -5.0
        angular:
          z:
            has_velocity_limits    : true
            max_velocity           : 2.0
            min_velocity           : -2.0
            has_acceleration_limits: true
            max_acceleration       : 3.0
            min_acceleration       : -3.0
            has_jerk_limits        : true
            max_jerk               : 5.0
            min_jerk               : -5.0

