[General]
exec_mode=0
ui_lang=1

[nav]
_migrated=1
loco_inflation=0.3
loco_max_vel=0.5
loco_xy_tol=0.1
loco_yaw_tol=0.4
mutual=true
planner_tb3_global=자동 (기본)
planner_waffle_slam=slam_toolbox (기본)
rotate=false
tb3_max_vel=0.22
tb3_xy_tol=0.05
tb3_yaw_tol=0.17
zones=true
