# Filter Params
min_particles: 1000
max_particles: 3000
kld_err: 0.02
kld_z: 0.98
update_min_d: 0.2
update_min_a: 0.16
resample_interval: 1
transform_tolerance: 0.5
save_pose_rate: 0.5

# Laser Model Params
laser_model_type: likelihood_field
laser_max_beams: 150
laser_max_range: 18.0
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0

# Odometry Model Params
odom_frame_id: odom
odom_model_type: diff
odom_alpha1: 1.0
odom_alpha2: 0.4
odom_alpha3: 0.8
odom_alpha4: 0.2

# Etc.
gui_publish_rate: 50.0